/* Formatted on 4/23/2018 12:40:45 PM (QP5 v5.227.12220.39754) */
  SELECT BQC.PID,
         BQC.APPLIANCE_TYPE_CODE,
         AI.APPLIANCE_NAME,
         AI.APPLIANCE_RATE,
         BQC.CUSTOMER_ID,
         BQC.OLD_APPLIANCE_QNT,
         BQC.OLD_APPLIANCE_QNT_BILLCALL,
         BQC.NEW_APPLIANCE_QNT,
         BQC.NEW_APPLIANCE_QNT_BILLCAL,
         (BQC.NEW_APPLIANCE_QNT_BILLCAL - BQC.NEW_APPLIANCE_QNT) * 2
            TOTAL_PARTIAL_DISS_QNT,
         BQC.TOTAL_PDISCONNECTED_QNT,
           BQC.TOTAL_TDISCONNECTED_QNT
         - ( (BQC.NEW_APPLIANCE_QNT_BILLCAL - BQC.NEW_APPLIANCE_QNT) * 2)
            TOTAL_TDISCONNECTED_QNT
    FROM BURNER_QNT_CHANGE BQC, APPLIANCE_INFO AI
   WHERE     BQC.APPLIANCE_TYPE_CODE = AI.APPLIANCE_ID
         AND PID IN (  SELECT MAX (PID)
                         FROM BURNER_QNT_CHANGE
                        WHERE CUSTOMER_ID = '110105769'
                     GROUP BY APPLIANCE_TYPE_CODE)
ORDER BY BQC.APPLIANCE_TYPE_CODE